# Generated by Django 4.2 on 2025-11-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_v1', '0004_categoria_produtos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tabela de Produtos',
                'verbose_name_plural': 'Tabelas de Produtos',
                'ordering': ('nome',),
            },
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuário'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='papel',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('operator', 'Operador'), ('visualizador', 'Visualizador')], default='operator', max_length=20, verbose_name='Papel'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tabelas_permitidas',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='inventario_v1.tabelaprodutos', verbose_name='Tabelas Permitidas'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='tabelas',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='inventario_v1.tabelaprodutos', verbose_name='Tabelas'),
        ),
    ]
