# Generated by Django 5.2.4 on 2025-07-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_finalizar_fk_metricas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='dataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='dataModificacao',
            new_name='data_modificacao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='dataValidade',
            new_name='data_validade',
        ),
        migrations.AddField(
            model_name='produto',
            name='checar_periodicamente',
            field=models.BooleanField(default=False, help_text='Marque para ativar checagem periódica.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cota_minima',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade mínima desejada para este produto.'),
        ),
        migrations.AddField(
            model_name='produto',
            name='intervalo_tipo',
            field=models.CharField(blank=True, choices=[('dias', 'Dias'), ('meses', 'Meses')], default='dias', help_text='Tipo de intervalo.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='intervalo_valor',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Intervalo entre verificações (ex: 30).', null=True),
        ),
        migrations.DeleteModel(
            name='CompraRecorrente',
        ),
    ]
