# Generated by Django 5.2.4 on 2025-07-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_datacadastro_produto_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='precisa_alerta_cota',
            field=models.BooleanField(default=False, help_text='Marque para ativar alerta de cota mínima.'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cota_minima',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade mínima desejada para este produto.'),
        ),
    ]
